const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('cambuzAPI', {
  openFile: () => ipcRenderer.invoke('dialog-open-file'),
  readFile: (filePath) => ipcRenderer.invoke('read-file', filePath),
  getPrinters: () => ipcRenderer.invoke('list-printers'),
  printPdf: (pdfBytes, options) => ipcRenderer.invoke('print-pdf', pdfBytes, options),
  onMenuPrint: (callback) => ipcRenderer.on('menu-print', callback),
  onMenuOpenFile: (callback) => ipcRenderer.on('menu-open-file', callback),
  onMenuCloseFile: (callback) => ipcRenderer.on('menu-close-file', callback),
  onMenuZoomIn: (callback) => ipcRenderer.on('menu-zoom-in', callback),
  onMenuZoomOut: (callback) => ipcRenderer.on('menu-zoom-out', callback),
  onMenuFitPage: (callback) => ipcRenderer.on('menu-fit-page', callback),
  onMenuFitWidth: (callback) => ipcRenderer.on('menu-fit-width', callback),
  onMenuPrevPage: (callback) => ipcRenderer.on('menu-prev-page', callback),
  onMenuNextPage: (callback) => ipcRenderer.on('menu-next-page', callback),
  onMenuToggleTheme: (callback) => ipcRenderer.on('menu-toggle-theme', callback),
  onMenuFind: (callback) => ipcRenderer.on('menu-find', callback),
  onMenuSelectAll: (callback) => ipcRenderer.on('menu-select-all', callback),
  onMenuRotateCW: (callback) => ipcRenderer.on('menu-rotate-cw', callback),
  onMenuRotateCCW: (callback) => ipcRenderer.on('menu-rotate-ccw', callback),
  onMenuFullscreen: (callback) => ipcRenderer.on('menu-fullscreen', callback),
  onMenuSidebar: (callback) => ipcRenderer.on('menu-sidebar', callback),
  onMenuShortcuts: (callback) => ipcRenderer.on('menu-shortcuts', callback),
});
